export const sdList = [
  {SD_EN_NM: "busan", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "chungbuk", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "chungnam", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "daegu", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "daejeon", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "dataTime", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "gangwon", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "gwangju", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "gyeongbuk", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "gyeonggi", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "gyeongnam", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "incheon", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "itemCode", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "jeju", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "jeonbuk", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "jeonnam", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "sejong", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "seoul", SD_CD: "", SD_NM: ""},
  {SD_EN_NM: "ulsan", SD_CD: "", SD_NM: ""},
]
// {
//   _returnType: "json",
//   busan: "24",
//   chungbuk: "27",
//   chungnam: "22",
//   daegu: "31",
//   daejeon: "15",
//   dataGubun: "1",
//   dataTerm: "",
//   dataTime: "2019-01-17 10:00",
//   gangwon: "27",
//   gwangju: "28",
//   gyeongbuk: "19",
//   gyeonggi: "39",
//   gyeongnam: "20",
//   incheon: "31",
//   itemCode: "10008",
//   jeju: "11",
//   jeonbuk: "31",
//   jeonnam: "17",
//   numOfRows: "10",
//   pageNo: "1",
//   resultCode: "",
//   resultMsg: "",
//   searchCondition: "",
//   sejong: "20",
//   seoul: "33",
//   serviceKey: "",
//   totalCount: "",
//   ulsan: "17"
//   },
  